# Generated by Django 5.1.1 on 2024-10-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options_news_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='upload_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
